spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动类名称
    url: jdbc:mysql://localhost:3306/tlias
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置mybatis的日志, 指定输出到控制台
    map-underscore-to-camel-case: true # 开启mybatis的驼峰命名自动映射开关 a_column ------> aCloumn
oss:
  cloudflare:
    access-key-id: ${OSS_ACCESS_KEY:default_value} # 请以环境变量的方式配置密钥
    secret-access-key: ${OSS_SECRET_ACCESS_KEY:default_value}
    bucket-name: tlias
    endpoint: https://40ddbfd0116e0d1a2d151df3ab831be3.r2.cloudflarestorage.com
    region: auto
key-generate:
  algorithm: HmacSHA256
  key-size: 256
  fixed-rate: 86400000 # 1 day in milliseconds
jwt:
  expiration: 86400000 # 1 day in milliseconds
